var ALIASES = {};
ALIASES["ansi_term"] = {};
ALIASES["bitflags"] = {};
ALIASES["downcast_rs"] = {};
ALIASES["libc"] = {};
ALIASES["strsim"] = {};
ALIASES["textwrap"] = {};
ALIASES["unicode_width"] = {};
ALIASES["vec_map"] = {};
