(function() {var implementors = {};
implementors["num_traits"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"num_traits/struct.ParseFloatError.html\" title=\"struct num_traits::ParseFloatError\">ParseFloatError</a>",synthetic:true,types:["num_traits::ParseFloatError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"enum\" href=\"num_traits/enum.FloatErrorKind.html\" title=\"enum num_traits::FloatErrorKind\">FloatErrorKind</a>",synthetic:true,types:["num_traits::FloatErrorKind"]},];
implementors["pir_8_emu"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"pir_8_emu/struct.Cpu.html\" title=\"struct pir_8_emu::Cpu\">Cpu</a>",synthetic:true,types:["pir_8_emu::cpu::Cpu"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"pir_8_emu/isa/struct.GeneralPurposeRegister.html\" title=\"struct pir_8_emu::isa::GeneralPurposeRegister\">GeneralPurposeRegister</a>",synthetic:true,types:["pir_8_emu::isa::register::general::GeneralPurposeRegister"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"pir_8_emu/isa/struct.SpecialPurposeRegister.html\" title=\"struct pir_8_emu::isa::SpecialPurposeRegister\">SpecialPurposeRegister</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a>,&nbsp;</span>",synthetic:true,types:["pir_8_emu::isa::register::special::SpecialPurposeRegister"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
